### ISSUE TITLE
How to extract node value?

### ISSUE THREAD

**Issue by zen3ger** [RazrFalcon/rctree#1]
The `resvg` crate used to use `ego_tree` which had a `value()` function but `rctree` does not.

Is there something similar?

**Comment by RazrFalcon** [comment]
`borrow()` to get the `T` and `kind()` to get `NodeKind`.

PS: you should wait for 0.2 release. The current master is an extremely unstable.

**Comment by zen3ger** [comment]
Thanks!
Even if it's unstable, resvg is a great crate and essential to my hobby project.

Keep up the good work!
