### ISSUE TITLE
Implement Serialize and Deserialize

### ISSUE THREAD

**Issue by xfbs** [RazrFalcon/rctree#12]
How about adding an optional feature which makes the tree derive Serialize and Deserialize?

**Comment by RazrFalcon** [comment]
Serialize/Deserialize into what?

**Comment by xfbs** [comment]
I mean the Serialize and Deserialize traits from [serde](https://crates.io/crates/serde), so that it can be serialized into any data structure.

**Comment by RazrFalcon** [comment]
I'm not sure how it can look like, but patches are welcome.

**Comment by RazrFalcon** [comment]
Out of scope.
