### ISSUE TITLE
Upgrade to use `?` operator over `try_opt!`

### ISSUE THREAD

**Issue by hasezoey** [RazrFalcon/rctree#15]
I noticed this while looking through how to use this library (could not find examples), so i looked at the source and noticed that a macro named `try_opt!` exists, which basically is like using [`?` operator](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator) from what i know (can also be used after converting between Result and Option)

example (from what i know):
currently there is

https://github.com/RazrFalcon/rctree/blob/f8d23aa3ce13f5a17b408f0f5bef0bc54c296cf8/src/lib.rs#L151-L153

which could be replaced with

```rs
pub fn parent(&self) -> Option<Node<T>> {
    Some(Node(self.0.borrow().parent.as_ref()?.upgrade()?))
}
```

**Comment by RazrFalcon** [comment]
Thanks. This is a very old code.

**Comment by RazrFalcon** [comment]
Looks like `?` on `Option` was added in 1.22. 1.13 had `?` only for `Result`.

**Comment by hasezoey** [comment]
> Looks like `?` on `Option` was added in 1.22. 1.13 had `?` only for `Result`.

~~if it was added in 1.22, then how did the tests pass for 1.17.0?~~

nevermind, didnt see that my commit was failing, just that the PR was passing

Note: i also didnt see before writing this comment about 83f5951d43171c0f5eee1a6f36bd7ff491a6ce8b, that before (which the pr was based on), was not actually running the old version
