### ISSUE TITLE
Performance issue with the redundancy memory operations

### ISSUE THREAD

**Issue by yyzdtccjdtc** [RazrFalcon/rctree#17]
https://github.com/RazrFalcon/rctree/blob/d7bc84f867688549cdab2f39149b819a5e67e550/src/lib.rs#L632
https://github.com/RazrFalcon/rctree/blob/d7bc84f867688549cdab2f39149b819a5e67e550/src/lib.rs#L670
https://github.com/RazrFalcon/rctree/blob/d7bc84f867688549cdab2f39149b819a5e67e550/src/lib.rs#L735
https://github.com/RazrFalcon/rctree/blob/d7bc84f867688549cdab2f39149b819a5e67e550/src/lib.rs#L749

These four functions will have a lot of redundant memory operations that push values into the stack and pop the values out of the stack when they are called. If we add a #[inline(always)] tag to these functions, these memory operations will be eliminated.

According to my test with the svg example of printpdf library (https://github.com/fschutt/printpdf), the average execution time decreased from 5.8s to 5.19s, which is a 11.8% speedup.

Hope this information helps!

**Comment by RazrFalcon** [comment]
By using `#[inline(always)]` we will blow up the binary size significantly. In general, I rely on Rust to decide if we should inline functions of not.

**Comment by yyzdtccjdtc** [comment]
> By using `#[inline(always)]` we will blow up the binary size significantly. In general, I rely on Rust to decide if we should inline functions of not.

Based on the application I used as a benchmark, the binary size has only increased by 0.02% (71539784 B to 71553304 B) with `#[inline(always)]`. I would also like to say that because the Rust compiler focuses mainly on security and reliability, it is lacking in the aspect of optimization.

Anyway, thanks for the reply! I would appreciate it even more if you could take a little time to test it.

**Comment by RazrFalcon** [comment]
>Based on the application I used as a benchmark, the binary size has only increased by 0.02%

That's the problem. With inline, the more code calls inlined methods the more it bloats.

>it is lacking in the aspect of optimization

I'm sorry, but this is just isn't true. Performance is one the main goals of Rust.

There is not much to test, really. All those methods you've mentioned are too heavy. Here is cargo-bloat output for the `resvg` crate:

```
0.1%  0.2%  3.8KiB    usvg rctree::Node<T>::make_copy
0.0%  0.1%  1.3KiB    usvg rctree::NodeData<T>::detach
0.0%  0.1%  1.1KiB    usvg rctree::Node<T>::insert_after
0.0%  0.1%    976B    usvg rctree::Node<T>::_make_deep_copy
0.0%  0.1%    968B    usvg rctree::Node<T>::append
0.0%  0.0%    508B    usvg <rctree::Descendants<T> as core::iter::traits::iterator::Iterator>::next
0.0%  0.0%    468B    usvg <rctree::Children<T> as core::iter::traits::iterator::Iterator>::next
0.0%  0.0%    448B   resvg <rctree::Children<T> as core::iter::traits::iterator::Iterator>::next
0.0%  0.0%    372B rctree? <rctree::Descendants<T> as core::iter::traits::iterator::Iterator>::next
0.0%  0.0%    364B  rctree rctree::NodeEdge<T>::next_item
0.0%  0.0%    356B  rctree rctree::NodeEdge<T>::next_item
0.0%  0.0%    320B   resvg rctree::Node<T>::children
0.0%  0.0%    312B    usvg rctree::Node<T>::children
0.0%  0.0%    256B    usvg rctree::Node<T>::has_children
0.0%  0.0%     96B   resvg rctree::Node<T>::borrow
0.0%  0.0%     96B  rctree rctree::Node<T>::borrow
```

As you can see, Rust able to inline all the tiny methods itself.

Also, rctree is not the right data structure if you care about performance.
